### PR TITLE
fix: card size width

### PR DESCRIPTION
**Pull request by Charbel-t**

### CODE REVIEW

**Review by osamaakb — CHANGES_REQUESTED** [review]
why is this 350px now? it should stay pixels

**Comment by Charbel-t** [comment]
> why is this 350px now? it should stay pixels



> why is this 350px now? it should stay pixels

You mean %? If yes, well it didnt work in any way, keeping it 20% make it shrink a lot, and can't put 2 cards on same row, the only way to keep it normal size is by putting 1card/row and we don't want this, so the only way to make it happen was by converting the 20% into 350px...

**Comment by osamaakb** [comment]
you can make it work by making the size 100% and use the `Col` from `antd` and make the col span `8` so you have 3 cards at the same time, you shouldn't add fixed size here

**Comment by Charbel-t** [comment]
> you can make it work by making the size 100% and use the `Col` from `antd` and make the col span `8` so you have 3 cards at the same time, you shouldn't add fixed size here

I tried, need to make the span={24} which is the entire page width, so the card doesn't shrink, 
so after span=24, can't add more card on same row

**Comment by osamaakb** [comment]
> > you can make it work by making the size 100% and use the `Col` from `antd` and make the col span `8` so you have 3 cards at the same time, you shouldn't add fixed size here
> 
> I tried, need to make the span={24} which is the entire page width, so the card doesn't shrink,
> so after span=24, can't add more card on same row

did you get to fix this?

**Comment by Charbel-t** [comment]
> > > you can make it work by making the size 100% and use the `Col` from `antd` and make the col span `8` so you have 3 cards at the same time, you shouldn't add fixed size here
> > 
> > 
> > I tried, need to make the span={24} which is the entire page width, so the card doesn't shrink,
> > so after span=24, can't add more card on same row
> 
> did you get to fix this?

Done

**Review by osamaakb — APPROVED** [review]

**Pull request merged**
