### PR TITLE
feat: add feedbackForm component

### PR DESCRIPTION
**Pull request by Charbel-t**

### CODE REVIEW

**Review by osamaakb — COMMENTED** [review]
Very good job @Charbel-t , but when the user want to send us a message how can he send it without adding their email?

**Comment by Charbel-t** [comment]
> Very good job @Charbel-t , but when the user want to send us a message how can he send it without adding their email?

That's what I meant about the probability of facing a bug,, so when the user has an account (signing in etc..) like finding a way of taking his Email that he first use it for his account.... but my question was what if he was surfing in the website without making an account?... How he can send a feedback in this case??
If you remember u told me to not think that far and just do the shape structure

**Comment by osamaakb** [comment]
> > Very good job @Charbel-t , but when the user want to send us a message how can he send it without adding their email?
> 
> That's what I meant about the probability of facing a bug,, so when the user has an account (signing in etc..) like finding a way of taking his Email that he first use it for his account.... but my question was what if he was surfing in the website without making an account?... How he can send a feedback in this case??
> If you remember u told me to not think that far and just do the shape structure

Ok, can you please add a field email so you can get the user email and make it function too

**Comment by Charbel-t** [comment]
> > > Very good job @Charbel-t , but when the user want to send us a message how can he send it without adding their email?
> > 
> > 
> > That's what I meant about the probability of facing a bug,, so when the user has an account (signing in etc..) like finding a way of taking his Email that he first use it for his account.... but my question was what if he was surfing in the website without making an account?... How he can send a feedback in this case??
> > If you remember u told me to not think that far and just do the shape structure
> 
> Ok, can you please add a field email so you can get the user email and make it function too

I made the required changes, may you please merge it if everything is OK so I can pass it to Mariam to add the email.js fonction

**Comment by osamaakb** [comment]
Looks good, I think it's better that you add the email functionality take a look at this I'm sure it will help you 
#66

**Review by osamaakb — APPROVED** [review]

**Pull request merged**
